spring.application.name=peffy-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/peffydb
spring.datasource.username= peffyuser
spring.datasource.password=peffypsw

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.jpa.show-sql=true